name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image for app
      - name: Build App Docker image
        run: |
          docker build -t mmarmal/tasks-app:latest ./app

      # 4. Push Docker image to Docker Hub
      - name: Push App Docker image
        run: |
          docker push mmarmal/tasks-app:latest
